// rag-ui/src/app/auth/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';

import { httpErrorDetail } from '../../api-error';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrl: '../auth.scss',
})
export class LoginComponent {
  private readonly router = inject(Router);
  private readonly authService = inject(AuthService);

  protected username = '';
  protected password = '';
  protected readonly busy = signal(false);
  protected readonly error = signal<string | null>(null);

  protected login(): void {
    if (this.busy()) return;

    const username = this.username.trim();
    const password = this.password;

    if (!username) {
      this.error.set('Username is required.');
      return;
    }
    if (username.length > 50) {
      this.error.set('Username must not exceed 50 characters.');
      return;
    }
    if (!password) {
      this.error.set('Password is required.');
      return;
    }

    this.busy.set(true);
    this.error.set(null);

    this.authService
      .login(username, password)
      .pipe(finalize(() => this.busy.set(false)))
      .subscribe({
        next: () => {
          void this.router.navigate(['/home']);
        },
        error: (e: unknown) => {
          this.error.set(httpErrorDetail(e));
        },
      });
  }

  protected goToSignup(): void {
    void this.router.navigate(['/signup']);
  }
}

<div class="auth-page">
  <div class="auth-card">

    <div class="auth-brand">
      <div class="brand-icon">
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </div>
      <span class="brand-name">RAGStudio</span>
    </div>

    <h1 class="auth-title">Welcome back</h1>
    <p class="auth-subtitle">Sign in to access your document workspace</p>

    <form (ngSubmit)="login()">
      <div class="form-field">
        <label for="username">Username</label>
        <input
          id="username"
          type="text"
          [(ngModel)]="username"
          name="username"
          required
          autocomplete="username"
          [disabled]="busy()"
          placeholder="Enter your username"
        />
      </div>

      <div class="form-field">
        <label for="password">Password</label>
        <input
          id="password"
          type="password"
          [(ngModel)]="password"
          name="password"
          required
          autocomplete="current-password"
          [disabled]="busy()"
          placeholder="Enter your password"
        />
      </div>

      @if (error(); as errorMessage) {
        <div class="error-banner" aria-live="assertive">
          <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
          </svg>
          {{ errorMessage }}
        </div>
      }

      <button type="submit" class="btn-submit" [disabled]="busy() || !username || !password">
        @if (busy()) { Signing in… } @else { Sign In }
      </button>
    </form>

    <div class="auth-footer">
      Don't have an account?
      <button type="button" class="link-btn" (click)="goToSignup()">Create one</button>
    </div>

  </div>
</div>

// rag-web/src/app/login/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { useAuth } from "@/context/AuthContext";
import { httpErrorDetail } from "@/lib/apiError";
import "../styles/auth.scss";

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuth();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (busy) return;

    const user = username.trim();
    if (!user) {
      setError("Username is required.");
      return;
    }
    if (user.length > 50) {
      setError("Username must not exceed 50 characters.");
      return;
    }
    if (!password) {
      setError("Password is required.");
      return;
    }

    setBusy(true);
    setError(null);
    try {
      await login(user, password);
      router.push("/home");
    } catch (err) {
      setError(httpErrorDetail(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-card">
        <div className="auth-brand">
          <div className="brand-icon">
            <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path
                d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <span className="brand-name">RAGStudio</span>
        </div>

        <h1 className="auth-title">Welcome back</h1>
        <p className="auth-subtitle">Sign in to access your document workspace</p>

        <form onSubmit={onSubmit}>
          <div className="form-field">
            <label htmlFor="username">Username</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              name="username"
              required
              autoComplete="username"
              disabled={busy}
              placeholder="Enter your username"
            />
          </div>

          <div className="form-field">
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              name="password"
              required
              autoComplete="current-password"
              disabled={busy}
              placeholder="Enter your password"
            />
          </div>

          {error && (
            <div className="error-banner" aria-live="assertive">
              <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path
                  d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                />
              </svg>
              {error}
            </div>
          )}

          <button
            type="submit"
            className="btn-submit"
            disabled={busy || !username || !password}
          >
            {busy ? "Signing in…" : "Sign In"}
          </button>
        </form>

        <div className="auth-footer">
          Don&apos;t have an account?{" "}
          <button
            type="button"
            className="link-btn"
            onClick={() => router.push("/signup")}
          >
            Create one
          </button>
        </div>
      </div>
    </div>
  );
}
