// rag-ui/src/app/auth/signup/signup.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';

import { httpErrorDetail } from '../../api-error';
import { AuthService } from '../auth.service';

const USERNAME_RE = /^[a-zA-Z0-9_-]+$/;

@Component({
  selector: 'app-signup',
  imports: [CommonModule, FormsModule],
  templateUrl: './signup.component.html',
  standalone: true,
  styleUrl: '../auth.scss',
})
export class SignupComponent {
  private readonly router = inject(Router);
  private readonly authService = inject(AuthService);

  protected username = '';
  protected password = '';
  protected confirmPassword = '';
  protected readonly busy = signal(false);
  protected readonly error = signal<string | null>(null);

  protected signup(): void {
    if (this.busy()) return;

    const username = this.username.trim();

    if (username.length < 3) {
      this.error.set('Username must be at least 3 characters.');
      return;
    }
    if (username.length > 50) {
      this.error.set('Username must not exceed 50 characters.');
      return;
    }
    if (!USERNAME_RE.test(username)) {
      this.error.set('Username may only contain letters, numbers, hyphens, and underscores.');
      return;
    }
    if (this.password.length < 6) {
      this.error.set('Password must be at least 6 characters.');
      return;
    }
    if (this.password.length > 100) {
      this.error.set('Password must not exceed 100 characters.');
      return;
    }
    if (this.password !== this.confirmPassword) {
      this.error.set('Passwords do not match.');
      return;
    }

    this.busy.set(true);
    this.error.set(null);

    this.authService
      .signup(username, this.password)
      .pipe(finalize(() => this.busy.set(false)))
      .subscribe({
        next: () => {
          void this.router.navigate(['/login']);
        },
        error: (e: unknown) => {
          this.error.set(httpErrorDetail(e));
        },
      });
  }

  protected goToLogin(): void {
    void this.router.navigate(['/login']);
  }
}

<div class="auth-page">
  <div class="auth-card">

    <div class="auth-brand">
      <div class="brand-icon">
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </div>
      <span class="brand-name">RAGStudio</span>
    </div>

    <h1 class="auth-title">Create account</h1>
    <p class="auth-subtitle">Get started with your document workspace</p>

    <form (ngSubmit)="signup()">
      <div class="form-field">
        <label for="username">Username</label>
        <input
          id="username"
          type="text"
          [(ngModel)]="username"
          name="username"
          required
          minlength="3"
          maxlength="50"
          autocomplete="username"
          [disabled]="busy()"
          placeholder="Letters, numbers, _ or - (3–50 chars)"
        />
      </div>

      <div class="form-field">
        <label for="password">Password</label>
        <input
          id="password"
          type="password"
          [(ngModel)]="password"
          name="password"
          required
          minlength="6"
          autocomplete="new-password"
          [disabled]="busy()"
          placeholder="Choose a password (min 6 chars)"
        />
      </div>

      <div class="form-field">
        <label for="confirmPassword">Confirm Password</label>
        <input
          id="confirmPassword"
          type="password"
          [(ngModel)]="confirmPassword"
          name="confirmPassword"
          required
          autocomplete="new-password"
          [disabled]="busy()"
          placeholder="Re-enter your password"
        />
      </div>

      @if (error(); as errorMessage) {
        <div class="error-banner" aria-live="assertive">
          <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
          </svg>
          {{ errorMessage }}
        </div>
      }

      <button type="submit" class="btn-submit" [disabled]="busy() || !username || !password || !confirmPassword">
        @if (busy()) { Creating account… } @else { Create Account }
      </button>
    </form>

    <div class="auth-footer">
      Already have an account?
      <button type="button" class="link-btn" (click)="goToLogin()">Sign in</button>
    </div>

  </div>
</div>

// rag-web/src/app/signup/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { useAuth } from "@/context/AuthContext";
import { httpErrorDetail } from "@/lib/apiError";
import "../styles/auth.scss";

const USERNAME_RE = /^[a-zA-Z0-9_-]+$/;

export default function SignupPage() {
  const router = useRouter();
  const { signup } = useAuth();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (busy) return;

    const user = username.trim();
    if (user.length < 3) {
      setError("Username must be at least 3 characters.");
      return;
    }
    if (user.length > 50) {
      setError("Username must not exceed 50 characters.");
      return;
    }
    if (!USERNAME_RE.test(user)) {
      setError("Username may only contain letters, numbers, hyphens, and underscores.");
      return;
    }
    if (password.length < 6) {
      setError("Password must be at least 6 characters.");
      return;
    }
    if (password.length > 100) {
      setError("Password must not exceed 100 characters.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setBusy(true);
    setError(null);
    try {
      await signup(user, password);
      router.push("/login");
    } catch (err) {
      setError(httpErrorDetail(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-card">
        <div className="auth-brand">
          <div className="brand-icon">
            <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path
                d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <span className="brand-name">RAGStudio</span>
        </div>

        <h1 className="auth-title">Create account</h1>
        <p className="auth-subtitle">Get started with your document workspace</p>

        <form onSubmit={onSubmit}>
          <div className="form-field">
            <label htmlFor="username">Username</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              name="username"
              required
              minLength={3}
              maxLength={50}
              autoComplete="username"
              disabled={busy}
              placeholder="Letters, numbers, _ or - (3–50 chars)"
            />
          </div>

          <div className="form-field">
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              name="password"
              required
              minLength={6}
              autoComplete="new-password"
              disabled={busy}
              placeholder="Choose a password (min 6 chars)"
            />
          </div>

          <div className="form-field">
            <label htmlFor="confirmPassword">Confirm Password</label>
            <input
              id="confirmPassword"
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              name="confirmPassword"
              required
              autoComplete="new-password"
              disabled={busy}
              placeholder="Re-enter your password"
            />
          </div>

          {error && (
            <div className="error-banner" aria-live="assertive">
              <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path
                  d="M12 8v4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                />
              </svg>
              {error}
            </div>
          )}

          <button
            type="submit"
            className="btn-submit"
            disabled={busy || !username || !password || !confirmPassword}
          >
            {busy ? "Creating account…" : "Create Account"}
          </button>
        </form>

        <div className="auth-footer">
          Already have an account?{" "}
          <button
            type="button"
            className="link-btn"
            onClick={() => router.push("/login")}
          >
            Sign in
          </button>
        </div>
      </div>
    </div>
  );
}
